### ISSUE TITLE
Master crash - error converting YAML to JSON

### ISSUE THREAD

**Issue by D1abloRUS** [determined-ai/determined#1742]
Hi, if you use dot and slash in labels:
```yaml
scheduler:
  resource_provider:
    type: "kubernetes"
    namespace: default
    max_slots_per_pod: 10
    master_service_name: test-determined-ai

task_container_defaults:
  cpu_pod_spec:
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        helm.sh/chart: "determined-ai-0.1.61"
        app.kubernetes.io/name: "test-determined-ai"
        app.kubernetes.io/instance: "test"
        app.kubernetes.io/managed-by: "Helm"
```

master crash:
```bash
error converting YAML to JSON: yaml: line 74: mapping values are not allowed in this context
error unmarshal yaml configuration file
main.mergeConfigBytesIntoViper
	/home/circleci/project/master/cmd/determined-master/root.go:111
main.initializeConfig
	/home/circleci/project/master/cmd/determined-master/root.go:69
main.runRoot
	/home/circleci/project/master/cmd/determined-master/root.go:40
main.glob..func1
	/home/circleci/project/master/cmd/determined-master/root.go:29
github.com/spf13/cobra.(*Command).execute
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846
github.com/spf13/cobra.(*Command).ExecuteC
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/project/master/cmd/determined-master/main.go:12
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```
