### ISSUE TITLE
A problem about mounting distributed file system

### ISSUE THREAD

**Issue by fengzf-github** [determined-ai/determined#4475]
Hello, does determined currently support mounting Minio file system？

The following is the error in mounting the Minio file system during my training model bub task：

# config.yaml

```
name: test001
defaults:
    - data: s3
    - profiling: disabled
    - searcher: single
    - hyperparameters:
        - base
        - ann_file

checkpoint_storage:
  save_trial_latest: 1
  type: s3
  bucket: test002-bucket
  access_key: minio
  secret_key: minio@123
  endpoint_url: http://192.168.40.11:9000/
  prefix: /output

min_validation_period:
  batches: 72

environment:
  image:
    gpu: determinedai/model-hub-mmdetection:0.18.1-dev0
  environment_variables:
      - OMP_NUM_THREADS=1 # Following pytorch dtrain, this environment variable is set to 1 to avoid overloading the system.

resources:
  slots_per_trial: 2 # max number of GPUs a trial is allowed to individually use
  shm_size: 200000000000
entrypoint: python3 -m determined.launch.torch_distributed --trial model_hub.mmdetection:MMDetTrial
```
# base.yaml
```
global_batch_size: 2
config_file: /mmdetection/configs/faster_rcnn/faster_rcnn_r50_caffe_fpn_1x_coco.py
merge_config: null

use_pretrained: false
clip_grads: false
# Config for MultiStepLR scheduler
step1: 72 # 8 epochs * 9 batches per epoch
step2: 99 # 11 epochs * 9 batches per epoch
warmup: 'linear'
warmup_iters: 50
warmup_ratio: 0.001
gamma: 0.1
```
# s3.yaml
```
file_client_args:
  backend: s3
  bucket_name: test001-bucket
  access_key: minio
  secret_key: minio@123
  endpoint_url: http://192.168.40.11:9000/
```

# ann_file.yaml
```
override_mmdet_config:
  data.train.ann_file:  /run/determined/workdir/data/coco/annotations/instances_train2017.json
  data.val.ann_file: /run/determined/workdir/data/coco/annotations/instances_val2017.json
```

# log
```
<info> [2022-07-05 16:42:59]
[301ab4ae] [26] root: Validating checkpoint storage ... <info> [2022-07-05 16:42:59]
[8cd738a1] [26] root: Uploading to s3: output/4e01826d-2742-4265-a180-873039e8bc1d/4e01826d-2742-4265-a180-873039e8bc1d <error> [2022-07-05 16:42:59]
[8cd738a1] [26] root: Checkpoint storage validation failed: Failed to upload /tmp/4e01826d-2742-4265-a180-873039e8bc1d/VALIDATE.txt to test002-bucket/output/4e01826d-2742-4265-a180-873039e8bc1d/VALIDATE.txt: An error occurred (AccessDenied) when calling the PutObject operation: S3 API Request made to Console port. S3 Requests should be sent to API port. <none> [2022-07-05 16:42:59]
[8cd738a1] + wait_child_exit=1 <none> [2022-07-05 16:42:59]
[8cd738a1] + set -e <none> [2022-07-05 16:42:59]
[8cd738a1] + '[' -z '' ']' <none> [2022-07-05 16:42:59]
[8cd738a1] + exit 1 <none> [2022-07-05 16:42:59]
[8cd738a1] + source /run/determined/task-logging-teardown.sh <none> [2022-07-05 16:42:59]
[8cd738a1] ++ '[' -n '' ']' <info> [2022-07-05 16:42:59]
[301ab4ae] [26] root: Uploading to s3: output/7868d863-dc59-4a29-9a6b-df6ee6e0ed51/7868d863-dc59-4a29-9a6b-df6ee6e0ed51 <error> [2022-07-05 16:42:59]
[301ab4ae] [26] root: Checkpoint storage validation failed: Failed to upload /tmp/7868d863-dc59-4a29-9a6b-df6ee6e0ed51/VALIDATE.txt to test002-bucket/output/7868d863-dc59-4a29-9a6b-df6ee6e0ed51/VALIDATE.txt: An error occurred (AccessDenied) when calling the PutObject operation: S3 API Request made to Console port. S3 Requests should be sent to API port. <error> [2022-07-05 16:42:59]
[8cd738a1] container failed with non-zero exit code: container failed with non-zero exit code: 1 (exit code 1) <error> [2022-07-05 16:42:59]
[301ab4ae] container failed with non-zero exit code: error while killing container: Error response from daemon: Cannot kill container: dfc8adb715c9838816767c60b712af215ab84885101565c431c13284dfb04d97: Container dfc8adb715c9838816767c60b712af215ab84885101565c431c13284dfb04d97 is not running 
```
