### ISSUE TITLE
💡[feat] Support for configuring elevated privileges for notebooks 

### ISSUE THREAD

**Issue by tybritten** [determined-ai/determined#5774]
### Describe the problem

The pachyderm jupyter lab extention mounts repos to the filesystem in the notebook instance. To be able to do this we need the ability to configure additional capabilities, specifically:
```
                    allow_privilege_escalation=True,
                     run_as_user=0,
                     privileged=True,
                     capabilities=client.V1Capabilities(
                         add=['SYS_ADMIN']
```

### Describe the solution you'd like

the ability to set some of those pod values in the configuration of the notebook

**Comment by rb-determined-ai** [comment]
I'm a bit shaky on how these different settings you are listing interact.

If you set `privileged=True` and `run_as_user=0`, then what does `SYS_ADMIN` contribute?  And if you are `run_as_user=0`, what does `allow_privilege_escalation=True` offer?

Some more explanation of what your code snippet would apply to would be nice.  `client.V1Capabilities` sounds like maybe a k8s api call?  or a docker api call?

Lastly, we already support adding capabilities to containers in agent installations, via the `add_capabilities` field of the [environment section](https://docs.determined.ai/latest/reference/reference-training/experiment-config-reference.html#environment).  I don't suppose that meets the need you are seeking already?

**Comment by tybritten** [comment]
Yeah you're right, i was looking at two different things. What we need is `privileged=True` and `run_as_user=0`set on the pod for the notebook when it's created. What I do now is 
```
          securityContext:
              privileged: true
              runAsUser: 0
```
on the container in the pod. the docker equivalent would be `--privileged` and `--allow-root`

**Comment by msteffen** [comment]
Small detail, but my understanding is that `--privileged` and `SYS_ADMIN` are alternatives (per the [--privileged docs](https://github.com/docker/cli/blob/c780f7c4abaf67034ecfaa0611e03695cf9e4a3e/docs/reference/commandline/run.md#full-container-capabilities---privileged)) and I think we only need `SYS_ADMIN`, in case it matters.

**Comment by rb-determined-ai** [comment]
I think we have the `securityContext` field of the podspec blacklisted since it partially overlaps the fields available in the experiment config.  I recall we had plans on relaxing that requirement, but we have not executed those plans.

We can rectify that.

In the mean time, would it be at all reasonable for Determined to automatically add mounts to the container or pod at launch time?  That way containers can run without privileges?  We have some customers where --privileged would be an issue.

**Comment by chainlink** [comment]
> Small detail, but my understanding is that `--privileged` and `SYS_ADMIN` are alternatives (per the [--privileged docs](https://github.com/docker/cli/blob/c780f7c4abaf67034ecfaa0611e03695cf9e4a3e/docs/reference/commandline/run.md#full-container-capabilities---privileged)) and I think we only need `SYS_ADMIN`, in case it matters.

@msteffen You are correct in that `--privileged` and `SYS_ADMIN` overlap, but I believe we actually need `--privileged` (In theory `SYS_ADMIN` should work, but I believe in practice we've needed to use `--privileged`)

@rb-determined-ai w.r.t. mounts, that's exactly what we end up doing in our "sidecar" mode with the extension to isolate the elevated privileges. 

This is what the Jupyterhub helm config looks like (roughly analogous to a kube manifest)

```
singleuser: # singleuser refers to the jupyter notebook that gets created by Hub
  defaultUrl: "/lab" # Ensure we're launching Jupyterlab, rather than jupyter notebooks
  image:
    name: pachyderm/notebooks-user # In sidecar mode the user can use their own image (need to install the jupyter extension 
    tag: v2.4.2
  extraEnv:
    "SIDECAR_MODE": "True"
  extraContainers:
    - name: mount-server-manager
      image: pachyderm/mount-server:2.4.2
      command: ["/bin/bash"]
      args: #TODO See if this can be removed if not setting up the config
        [
          "-c",
          "mount-server",
        ]
      volumeMounts:
        - name: shared-pfs
          mountPath: /pfs
          mountPropagation: Bidirectional
        - name: files
          mountPath: /config
      securityContext:
        privileged: true
        runAsUser: 0
  storage:
    extraVolumeMounts:
      - name: shared-pfs
        mountPath: /pfs
        mountPropagation: HostToContainer
    extraVolumes:
      - name: shared-pfs
        emptyDir: {}
```
