### ISSUE TITLE
💡[feat] NVIDIA Multi-Instance GPU (MIG) Support

### ISSUE THREAD

**Issue by TrevorM15** [determined-ai/determined#6204]
### Describe the problem

Currently the only option to inform determined of the number of GPUs a node has is with the `maxSlotsPerPod` field in the values.yaml file. However, Some GPUs that NVIDIA offers have the ability to partition the memory (MIG) for smaller workloads that don't saturate the GPU memory. In addition Nebuly offers a way to [dynamically partition GPUs. ](https://github.com/nebuly-ai/nos) Therefore, in order to better utilize resources, a nice feature would be the ability to specify MIG resources in something like `maxSlotsPerPod`.

### Describe the solution you'd like

Possible yaml to describe 2 40GB A100s and requesting 8 MIGs of 10GB each spread across the two GPUs. 
```yaml
maxSlotsPerPod:
  value: 2
  mig:
    - 1g.5gb: 7
    - 2g.10gb: 4
    - 3g.20gb: 2
```
```yaml
resources:
  slots_per_trial:
    2g.10gb: 8
```
