### ISSUE TITLE
🐛[bug] prometheus in version 23.4 not work.

### ISSUE THREAD

**Issue by kmilouh** [determined-ai/determined#7588]
### Describe the bug

The configuration to use prometheus in version 23.4 not work. 
After configure:
observability:
    enable_prometheus: true

the url {$DET_MASTER_ADDR}/prom/det-state-metrics returns 401 Unauthorized

### Reproduction Steps

1. I follow the steps in https://docs.determined.ai/latest/integrations/prometheus/prometheus.html 

### Expected Behavior

Show cluster usage in Grafana. 

### Screenshot

![image](https://github.com/determined-ai/determined/assets/13699090/80f7ad97-f04e-4aaa-b43a-812df008530c)

### Environment

- Device or hardware: PC
- OS: Ubuntu 22.04
- Browser Firefox
- Version 116.0.1 (64-bit)

**Comment by stoksc** [comment]
Hey, I think you will need to pass a bearer token. The scrape is failing with a 401. The browser is probably working because of our auth cookie.

You can pass a token to Prometheus in the config like:
```
  - job_name: "..."
    metrics_path: /debug/prom/metrics
    scheme: https
    authorization:
      type: Bearer
      credentials_file: determined-bearer-token.txt
    static_configs:
      - targets: ['...:443']
```
I've done this before, we a cron job writing the token daily with:
```
#!/bin/bash

curl https://gcloud.determined.ai/api/v1/auth/login -X POST -d '{"username": "...", "password": "..."}' -s |\
        jq -r .token >determined-bearer-token.txt
```

**Comment by stoksc** [comment]
if you look in prometheus, do you see any metrics? i wonder if it is an issue with the data or the graphs themselves.

**Comment by stoksc** [comment]
just checking, did you resolve this @kmilouh? if so, what was the issue.

**Comment by jgmke** [comment]
I'd like to know, too.  I'm working through the same issue.

**Comment by jgmke** [comment]
Found something...In the sample prometheus.yml, the endpoint configuration for the cadvisor-dcgm job reads as follows:

```
http_sd_configs:
  - follow_redirects: true
    refresh_interval: 1m
    url: http://det-master-address:8080/prom/det-http-sd-config
```

The instructions say to replace it with the correct master address, but it actually needs to point to the cadvisor and dcgm-exporter containers.

I replaced the above section in prometheus.yaml with the following and now I have a populated dashboard.

```
  static_configs:
  - targets:
     - dcgm-exporter:9400
     - cadvisor:8080
```

(I'm using docker dns for name resolution)

![image](https://github.com/determined-ai/determined/assets/10231941/77589ebe-a01e-4b47-bba4-36b5ffa40384)
