### ISSUE TITLE
Number of training steps is unclear when max_steps > 1 epoch

### ISSUE THREAD

**Issue by yitang** [determined-ai/determined#949]
I have a dataset that has 829 * 100 mini-batches. If I set max_steps to 9 and batches_per_step to 100 (default) then:

the training stopped before reaching to step 9 due to StopIteration exception, and the python process was terminated with "container failed with non-zero exit code: container failed with non-zero exit code: 1". immediately, another python process started to train for 6 steps (600 mini-batches), and it stopped with "INFO: Workload completed: <RUN_STEP (100): (34,64,10)> (duration 0:00:21.639865)" 

so it trained 14.29 (8.29 in the 1st run, plus 6 in the 2nd run) steps in total, also the 2nd run seems trained from scratch and does not use the parameter from the first run.

I was expecting to have 9 steps in total in one go.

 ``` yaml
description: siim_const_batch_1
environment:
  image: determinedai/environments:cuda-10.1-pytorch-1.4-tf-2.2-gpu-1
data:
  url: https://s3-us-west-2.amazonaws.com/determined-ai-test-data/pytorch_mnist.tar.gz
hyperparameters:
  learning_rate: 1.0
  global_batch_size: 32
  n_filters1: 32
  n_filters2: 64
  dropout1: 0.25
  dropout2: 0.5
checkpoint_policy: best
min_validation_period: 1  # in step
searcher:
  name: single
  metric: auc
  max_steps: 10  # 9 steps is ~ one epoch
  smaller_is_better: false
batches_per_step: 100 
```
